apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-frontend
  template:
    metadata:
      labels:
        app: llm-frontend
    spec:
      containers:
        - name: llm-frontend
          image: llm-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: BACKEND_URL
              value: "http://llm-python:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: llm-frontend
spec:
  type: NodePort
  selector:
    app: llm-frontend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
